apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  USERNAME: "{{ .Values.userConfig.username }}"
  HOME_URL: "{{ .Values.userConfig.homepageUrl }}"
  EMAIL_PREFIX: "{{ .Values.userConfig.emailPrefix }}"
  TARGET_URL: "{{ .Values.userConfig.targetUrl }}"
  LOG_LEVEL: "{{ .Values.userConfig.logLevel }}"
  HEADLESS: "{{ .Values.userConfig.headless }}"
